### ISSUE TITLE
Supported Python version(s)?

### ISSUE THREAD

**Issue by crolfe** [kennell/rai#5]
Which version of Python should we support?  

Python 2.7 is end of life in 2020, but given this is a brand new library, and RaiBlocks itself is a fairly nascent technology, there shouldn't be much, if any, legacy code out there that needs 2.7 support.  

Supporting both isn't too onerous using compatibility libraries such as `six`, but it's going to lock us out of using the newer features in 3.5+.  

My vote is to try to officially support 3.4+, and try for unofficial/best-effort support of 2.7.  

Either way, we should update the setup.py to reflect which version(s) we support, and look at testing against all supported versions using `tox` once CI gets setup.

**Comment by kennell** [comment]
I would like to support Python 3.4 and higher. With regards to Pyhton 2: i don't want to sacrifice anything for Py2 compability, as you said, it is end of life in <2 years.

By the way: TravisCI is already up and running, testing against 3.4, 3.5, 3.6. I will add the relevant classifiers in the setup.py file shortly.

**Comment by crolfe** [comment]
Awesome!
